name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor', 'ci']
change-template: '- $TITLE (#$NUMBER)'
sort-direction: ascending
template: |
  ## Changes
  $CHANGES
