# golangci-lint configuration
# - paralleltest: enforces t.Parallel() in tests; use //nolint:paralleltest with justification for serial tests
# - testpackage: warns if tests use the same package as the code under test; prefer _test package for public API tests
# See CONTRIBUTING.md for test best practices.

run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - goimports
    - gocognit
    - ineffassign
    - misspell
    - wastedassign
    - paralleltest
    - testpackage
    - tagliatelle
    - gocritic
    - gosec
  presets:
    - bugs
issues:
  exclude-use-default: false
