version: 2
# golangci-lint configuration
# - paralleltest: enforces t.Parallel() in tests; use //nolint:paralleltest with justification for serial tests
# See CONTRIBUTING.md for test best practices.

run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - gocognit
    - ineffassign
    - misspell
    - wastedassign
    - paralleltest
    - gocritic
    - gosec
    - contextcheck
    - unused
    - dupl
    - nilnil
    - prealloc
    - unparam
    - dogsled
    - bodyclose
    - cyclop
    - errorlint
    - containedctx
    - whitespace
  presets:
    - bugs
  severity:
    errcheck: warning
    gocritic: warning
issues:
  exclude-use-default: false

linters-settings:
  cyclop:
    max-complexity: 13
  prealloc:
    simple: true
  revive:
    ignore-generated-header: true
    severity: warning
  contextcheck:
    # Warn if context.Context is not the first arg in exported funcs
    # (default is true)
    check-exported: true
    check-unexported: false
    allow-context-arg-in-structs: false
