version: 2
# golangci-lint configuration
# - paralleltest: enforces t.Parallel() in tests; use //nolint:paralleltest with justification for serial tests
# See CONTRIBUTING.md for test best practices.

run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - gocognit
    - ineffassign
    - misspell
    - wastedassign
    - paralleltest
    - gocritic
    - gosec
  presets:
    - bugs
issues:
  exclude-use-default: false
