run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - goimports
    - gocognit
    - ineffassign
    - misspell
    - wastedassign
  presets:
    - bugs
issues:
  exclude-use-default: false
