version: 2
# golangci-lint configuration
# - paralleltest: enforces t.Parallel() in tests; use //nolint:paralleltest with justification for serial tests
# See CONTRIBUTING.md for test best practices.

run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - gocognit
    - ineffassign
    - misspell
    - wastedassign
    - paralleltest
    - gocritic
    - gosec
    - contextcheck
    - unused
    - dupl
    - depguard
    - nilnil
    - prealloc
    - unparam
    - dogsled
    - bodyclose
    - gocyclo
  presets:
    - bugs
  severity:
    errcheck: warning
    gocritic: warning
issues:
  exclude-use-default: false

linters-settings:
  gocyclo:
    min-complexity: 15
  prealloc:
    simple: true
  depguard:
    list-type: blacklist
    packages:
      - github.com/pkg/errors
    packages-with-error-message:
      github.com/pkg/errors: "use Go 1.13+ standard errors instead of github.com/pkg/errors"
  goimports:
    local-prefixes: github.com/jingle2008/toolkit
  contextcheck:
    # Warn if context.Context is not the first arg in exported funcs
    # (default is true)
    check-exported: true
    check-unexported: false
    allow-context-arg-in-structs: false
