version: 2

project_name: toolkit

builds:
  - id: toolkit
    main: ./cmd/toolkit/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: jingle2008
    name: toolkit

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - '^wip:'
      - '^Merge pull request'
      - '^Merge branch'

signs:
  - artifacts: checksum
    args:
      - --batch
      - --yes
      - --armor
      - --detach-sign
      - --local-user
      - jingle2008@gmail.com
      - --output
      - ${signature}
      - ${artifact}
    signature: "${artifact}.sig"

# Only include if using GoReleaser v2.10 or later
brews:
  - name: toolkit
    directory: Formula
    repository:
      owner: jingle2008
      name: homebrew-toolkit
    homepage: https://github.com/jingle2008/toolkit
    description: "Toolkit CLI: cross-platform command-line tool for cloud & infra automation"
    install: |
      bin.install "toolkit"
    test: |
      system "#{bin}/toolkit", "--version"

homebrew_casks:
  - name: toolkit
    repository:
      owner: jingle2008
      name: homebrew-toolkit
    homepage: "https://github.com/jingle2008/toolkit"
    description: "Toolkit CLI: cross-platform command-line tool for cloud and infrastructure automation"
    binary: toolkit
