// Code generated by "stringer -type=Category"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Tenant-1]
	_ = x[LimitDefinition-2]
	_ = x[ConsolePropertyDefinition-3]
	_ = x[PropertyDefinition-4]
	_ = x[LimitTenancyOverride-5]
	_ = x[ConsolePropertyTenancyOverride-6]
	_ = x[PropertyTenancyOverride-7]
	_ = x[ConsolePropertyRegionalOverride-8]
	_ = x[PropertyRegionalOverride-9]
	_ = x[BaseModel-10]
	_ = x[ModelArtifact-11]
	_ = x[Environment-12]
	_ = x[ServiceTenancy-13]
	_ = x[GpuPool-14]
	_ = x[GpuNode-15]
	_ = x[DedicatedAICluster-16]
}

const _Category_name = "TenantLimitDefinitionConsolePropertyDefinitionPropertyDefinitionLimitTenancyOverrideConsolePropertyTenancyOverridePropertyTenancyOverrideConsolePropertyRegionalOverridePropertyRegionalOverrideBaseModelModelArtifactEnvironmentServiceTenancyGpuPoolGpuNodeDedicatedAICluster"

var _Category_index = [...]uint16{0, 6, 21, 46, 64, 84, 114, 137, 168, 192, 201, 214, 225, 239, 246, 253, 271}

func (i Category) String() string {
	i -= 1
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
