// Code generated by "stringer -type=Category"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CategoryUnknown-0]
	_ = x[Tenant-1]
	_ = x[LimitDefinition-2]
	_ = x[ConsolePropertyDefinition-3]
	_ = x[PropertyDefinition-4]
	_ = x[LimitTenancyOverride-5]
	_ = x[ConsolePropertyTenancyOverride-6]
	_ = x[PropertyTenancyOverride-7]
	_ = x[LimitRegionalOverride-8]
	_ = x[ConsolePropertyRegionalOverride-9]
	_ = x[PropertyRegionalOverride-10]
	_ = x[BaseModel-11]
	_ = x[ModelArtifact-12]
	_ = x[Environment-13]
	_ = x[ServiceTenancy-14]
	_ = x[GpuPool-15]
	_ = x[GpuNode-16]
	_ = x[DedicatedAICluster-17]
	_ = x[Alias-18]
}

const _Category_name = "CategoryUnknownTenantLimitDefinitionConsolePropertyDefinitionPropertyDefinitionLimitTenancyOverrideConsolePropertyTenancyOverridePropertyTenancyOverrideLimitRegionalOverrideConsolePropertyRegionalOverridePropertyRegionalOverrideBaseModelModelArtifactEnvironmentServiceTenancyGpuPoolGpuNodeDedicatedAIClusterAlias"

var _Category_index = [...]uint16{0, 15, 21, 36, 61, 79, 99, 129, 152, 173, 204, 228, 237, 250, 261, 275, 282, 289, 307, 312}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
