name: Test and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: make test
      - name: Run coverage
        run: make cover
      - name: Enforce coverage threshold
        run: |
          percentage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $percentage%"
          if (( $(echo "$percentage < 80" | bc -l) )); then
            echo "Coverage $percentage% is below 80% threshold"
            exit 1
          fi
